refactor: rename do.sh to db

diff --git a/tools/db b/tools/db
--- a/tools/db
+++ b/tools/db
@@ -2,7 +2,7 @@
 ###########################################################################
 ##                     Copyright (C) 2017 wystan
 ##
-##       filename: do.sh
+##       filename: db
 ##    description: 
 ##        created: 2017-01-05 16:22:50
 ##         author: wystan
@@ -25,7 +25,12 @@ function do_restore() {
         echo "ERROR: $1 does not exist, exit !!"
         return
     fi
+    psql -c "drop database if exists $db"
     psql -c "create database $db"
+    if [ $? -ne 0 ]; then
+        echo "ERROR: fail to create database $db"
+        return
+    fi
     psql -d $db -f $1
     echo "done"
 }
@@ -33,8 +38,8 @@ function do_restore() {
 function usage() {
 cat << !EOF
 usage: 
-    - do.sh backup
-    - do.sh restore <backup.sql>
+    - db backup
+    - db restore <backup.sql>
 
 !EOF
 }
